const D=[
    [1,"Software engineering: definition?","Systematic application of engineering approaches to software development: systematic methodology, disciplined & quantifiable approach, covering development, operation and maintenance."],
    [1,"Why is software engineering important?","Builds reliable, maintainable, scalable systems; reduces cost by minimising errors; copes with complexity, evolving requirements and teamwork."],
    [1,"Abstraction","Hiding unnecessary details and exposing only essential features to simplify complexity. E.g. car dashboard shows speed/fuel, not the engine."],
    [1,"Modularity","Dividing a system into small self-contained modules. Benefits: easier maintenance, parallel development, code reuse. E.g. auth, database, UI modules."],
    [1,"Encapsulation","Restricting access to parts of an object, exposing only necessary interfaces. Protects data integrity, enables loose coupling. E.g. private fields + public methods."],
    [1,"Abstraction vs encapsulation?","Abstraction hides complexity (what you see). Encapsulation restricts access to data/internals (what you can touch)."],
    [1,"Class vs object","A class is a blueprint; an object is an instance of it (Car class -> myCar)."],
    [1,"Inheritance & polymorphism","Mechanisms for creating hierarchies and dynamic behaviour, e.g. overriding methods."],
    [1,"C# type safety: 3 features","Strong type checking (no string into int), type inference (var name = \"John\"), generic types (List<T>). Catches errors at compile time."],
    [1,"C# memory management","Garbage collection auto-reclaims unused objects; resource management; IDisposable for deterministic cleanup of unmanaged resources (e.g. DB connections)."],
    [1,"CLR (Common Language Runtime)","Execution engine of .NET: memory management, exception handling, security. Uses JIT compilation and garbage collection."],
    [1,"JIT compilation","Converts intermediate code (IL) into machine code at runtime for performance."],
    [1,"BCL (Base Class Library)","Reusable classes/methods for common tasks: file I/O, data manipulation (sorting/searching), string handling & regex."],
    [1,".NET language independence","Multiple languages work together (e.g. C# and F#): interoperability, code sharing across teams."],
    [1,"Visual Studio features","IntelliSense (real-time suggestions/error detection), debugging tools (breakpoints, watches, call stack), extensions."],
    [1,"VS IDE components","Solution Explorer (files/dependencies), Properties Window (attributes of selected item), Output Window (build/runtime logs)."],
    [1,"First project type in VS","Console App (.NET Core), then write Hello World and run it."],
    [1,"Assessment weighting","Online test 50% + group coursework 50% (25% design/project mgmt/implementation; 25% algorithms & data structures)."],
    [1,"Online test format","On Moodle, random questions: multiple choice, short answer, matching; time limit."],
    [1,"Coursework rules","Group work but individual mark; only group leader submits; feedback within 15 working days."],
    [1,"Extenuating circumstances","Apply via UniHelp with evidence; not decided by academic staff; gives deferral/extension."],
    [1,"Plagiarism/collusion examples","Working together on individual work, getting others to do it, unreferenced online code, using AI tools (e.g. ChatGPT). Penalty: fail task or module."],
    
    [2,"git init / git clone","init creates a new repository; clone <url> copies an existing one."],
    [2,"Configure Git","git config user.name \"..\"; git config user.email \"..\"; core.editor code; git config --list to view."],
    [2,"Staging vs committing","git add <file> / git add . stages files; git commit -m \"msg\" records changes."],
    [2,"Remote commands","git remote add origin <url>; git push -u origin main; git fetch (download); git pull (fetch + merge)."],
    [2,"Branch commands","git branch <name> creates; git checkout <name> switches; git checkout -b <name> does both."],
    [2,"Fast-forward vs three-way merge","Fast-forward: no divergence, just moves pointer. Three-way: diverged branches, creates a new merge commit."],
    [2,"Resolving a merge conflict","Git marks conflicts in files; edit to resolve, then git add <file> and git commit."],
    [2,"Pull request workflow (Azure DevOps)","Push to feature branch -> create PR -> add reviewers/comments -> complete PR and merge to main."],
    [2,"Reviewer actions on a PR","Comment, suggest changes, approve; use Resolve Comments to address feedback."],
    [2,"Agile Manifesto: 4 values","Individuals & interactions > processes & tools; working software > comprehensive documentation; customer collaboration > contract negotiation; responding to change > following a plan."],
    [2,"Why Agile?","Traditional models: rigid, delayed feedback, slow delivery. Agile: faster value, flexibility, continuous feedback."],
    [2,"Key Agile principles","Deliver working software frequently; embrace changing requirements; daily business-developer collaboration; trust motivated individuals; reflect regularly."],
    [2,"Waterfall vs Agile","Waterfall: linear, sequential, limited flexibility. Agile: incremental, iterative, continuous improvement."],
    [2,"Scrum roles","Product Owner (represents stakeholders, prioritises backlog); Scrum Master (ensures Scrum practice, removes impediments); Development Team (delivers increments)."],
    [2,"Scrum events","Sprint Planning, Daily Standup, Sprint Review, Sprint Retrospective."],
    [2,"Scrum artifacts","Product Backlog (prioritised list); Sprint Backlog (tasks for current sprint); Increment (sum of completed items in a sprint)."],
    [2,"Sprint workflow order","Planning -> Daily standups -> Execution -> Review (demo to stakeholders) -> Retrospective (reflect/improve)."],
    [2,"Agile metrics","Velocity (story points completed); Burn-down chart (work done vs remaining); Cycle time (start to finish of a task)."],
    [2,"Azure DevOps key features","Boards (Kanban, backlogs), Repos (Git), Pipelines (automate builds/deployments)."],
    [2,"Azure Boards","Kanban boards, customisable columns/work item types; backlog management; requirements become user stories."],
    [2,"Azure Repos features","Pull requests, code reviews, branch policies to enforce standards."],
    [2,"Azure Pipelines (CI)","Automate build & test. Build triggers run on changes; YAML defines steps. Benefits: early defect detection, consistent quality."],
    [2,"Agile challenges","Resistance to change, hard to keep collaboration, distributed teams. Tips: Agile training, tools like Azure DevOps."],
    [2,"Spotify case study","Agile for innovation; Squad and Tribe models for team autonomy; faster releases."],
    [2,"Agile vs DevOps","Agile: iterative development & collaboration. DevOps: automation, integration, delivery. Together = faster, more reliable delivery."],
    [2,"SDLC: definition & benefits","Structured process for developing software; reduces risk, improves quality, streamlines team communication."],
    [2,"SDLC phases (in order)","Requirements Analysis -> Design & Architecture -> Implementation -> Testing -> Deployment & Maintenance."],
    [2,"Stakeholders","Individuals/groups impacted by the project (end-users, sponsors, regulators). Identify via interviews, surveys, stakeholder mapping."],
    [2,"Requirements gathering techniques","Use cases & user stories, workshops/brainstorming, observation, prototyping."],
    [2,"Functional vs non-functional","Functional: what should the system do? Non-functional: how should it perform?"],
    [2,"Requirements documents","FRS (Functional Requirement Spec), NFR (Non-Functional Spec), user stories/use case diagrams."],
    [2,"Design principles & outputs","Modularity, scalability, maintainability. Outputs: architecture diagrams, component specs, interface definitions."],
    [2,"Component design","Break system into independent modules and define their roles/interactions (payment, authentication, user management)."],
    [2,"Implementation best practices","Coding standards, version control (Git), regular code reviews. E.g. consistent indentation, meaningful names."],
    [2,"Why code reviews?","Catch bugs early, share knowledge, improve quality. Process: PR -> assign reviewers -> address feedback -> merge."],
    [2,"Testing types","Unit (individual components), Integration (interactions between components), System (whole system)."],
    
    [3,"Array: definition & characteristics","Elements in contiguous memory, zero-based index, fixed size after initialisation, same type, fast direct access."],
    [3,"When to use fixed-size arrays","When the number of elements is predetermined."],
    [3,"2D array vs jagged array","2D: grid/table in contiguous memory, faster access. Jagged: array of arrays with different sizes; extra reference memory but more flexible."],
    [3,"Common Array methods","Array.Sort(); Array.Resize(ref arr, newSize); Array.IndexOf(arr, value); Array.Copy(src, dest, length)."],
    [3,"List<T>","Dynamic array that auto-resizes; generic; implements IList; higher-level abstraction than arrays."],
    [3,"How does List<T> resize?","When capacity is exceeded, the internal array size doubles (efficient, minimises reallocation)."],
    [3,"When to use List<T>","When collection size changes frequently."],
    [3,"LinkedList","Node-based: each node holds data + reference to next (and optionally previous). Fast insert/delete (only references change); slower sequential access than arrays."],
    [3,"When to use LinkedList","Frequent insertions/deletions at arbitrary positions."],
    [3,"List<T> vs LinkedList","List<T>: contiguous array, fast index access, resize cost. LinkedList: nodes, efficient insert/delete, slower access."],
    
    [4,"Hash function","Converts a key into a fixed-size integer (hash code); should distribute uniformly to minimise collisions."],
    [4,"Good hash function properties","Deterministic, uniform, efficient."],
    [4,"Collision resolution methods","Separate chaining (linked list per slot); open addressing (next free slot via linear or quadratic probing)."],
    [4,"Load factor & resizing","Load factor = stored elements / number of slots. Rehash into a larger table when it exceeds a threshold."],
    [4,"Hash table average complexity","O(1) average for insertion, deletion, search."],
    [4,"Graph basics","Vertices (nodes/entities) and edges (connections/relationships)."],
    [4,"Directed vs undirected vs weighted","Directed: edges have direction (one-way streets). Undirected: no direction (friendships). Weighted: edges carry cost/distance."],
    [4,"Depth-First Search (DFS)","Explores as far as possible along each branch before backtracking."],
    [4,"Breadth-First Search (BFS)","Explores all vertices at the current depth level before going deeper."],
    [4,"Dijkstra's algorithm","Finds shortest path from a source vertex to all others in a weighted graph."],
    [4,"Practice topics listed","Linear probing & double hashing, cycle detection, topological sorting."],
    
    [5,"Primary key vs foreign key","Primary key: unique identifier of a record. Foreign key: field referencing another table's primary key."],
    [5,"Relationship types","One-to-one, one-to-many, many-to-many."],
    [5,"Normalisation","Organising data to reduce redundancy and improve integrity."],
    [5,"1NF / 2NF / 3NF","1NF: remove duplicate columns, separate tables for related data. 2NF: non-key attributes depend on the whole primary key. 3NF: remove transitive dependencies."],
    [5,"ER diagram components","Entities (Students, Courses), Attributes (Name, Age), Relationships (Students enrol in Courses)."],
    [5,"Schema design","Logical structure of a DB: tables, fields, data types, constraints."],
    [5,"Clustered vs non-clustered index","Clustered: sorts and stores rows physically in the table. Non-clustered: separate structure pointing to the data. Both speed up retrieval."],
    [5,"DDL / DML / DCL","DDL defines structure (CREATE TABLE). DML manipulates data (INSERT). DCL controls access (GRANT SELECT ON Students TO User1)."],
    [5,"CREATE TABLE example","CREATE TABLE Students (StudentID INT PRIMARY KEY, Name VARCHAR(100), Age INT);"],
    [5,"SELECT with WHERE","SELECT Name, Age FROM Students WHERE Age > 18;"],
    [5,"INSERT / UPDATE / DELETE","INSERT INTO Students (Name, Age) VALUES ('Alice', 20);\nUPDATE Students SET Age = 21 WHERE Name = 'Alice';\nDELETE FROM Students WHERE Age < 18;"],
    [5,"JOIN types","INNER: matching rows. LEFT: all left + matching right. RIGHT: all right + matching left. FULL OUTER: all rows from both."],
    [5,"INNER JOIN example","SELECT Students.Name, Courses.Title FROM Students INNER JOIN Enrolments ON Students.StudentID = Enrolments.StudentID INNER JOIN Courses ON Enrolments.CourseID = Courses.CourseID;"],
    
    [6,"Connection string","Defines how an app connects to a DB: \"Server=..;Database=..;User Id=..;Password=..;\". Don't hardcode; use config files."],
    [6,"Connection pooling","Reuses existing connections: less overhead, faster execution."],
    [6,"Transaction handling (ADO.NET)","Ensures integrity across operations: conn.BeginTransaction(); try { ...; Commit(); } catch { Rollback(); throw; } inside a using block."],
    [6,"Connected vs disconnected architecture","Connected: connection stays open during operations. Disconnected: DataSet/DataTable used to work offline."],
    [6,"ADO.NET best practices","Use 'using' statements to manage resources; keep connection strings in config files."],
    [6,"EF Core Code-First: 3 steps","Entity class design (classes map to tables); relationships mapping (1:1, 1:many, many:many); migrations to update schema."],
    [6,"EF migration commands","dotnet ef migrations add InitialCreate\ndotnet ef database update"],
    [6,"Database-First approach","Generate C# classes/context from an existing schema: dotnet ef dbcontext scaffold \"conn\" Microsoft.EntityFrameworkCore.SqlServer (Scaffold-DbContext)."],
    [6,"Code-First vs Database-First","Code-First: create DB from code; ideal for greenfield projects. Database-First: start from existing DB; best for legacy systems."],
    [6,"LINQ to Entities syntax","Query: from s in context.Students where s.Age > 18 select s;\nMethod: context.Students.Where(s => s.Age > 18).ToList();"],
    [6,"LINQ performance tips","Use AsNoTracking() for read-only queries; minimise number of DB calls."],
    [6,"ORM / EF Core advantage","ORM maps objects to tables so you do CRUD with C# objects and LINQ instead of raw SQL (vs ADO.NET)."]
];