// One explanation per question, in the SAME ORDER as quiz.js (116 total)
const EX=[
    // Week 1 (25)
    "It is a systematic, disciplined and quantifiable approach covering development, operation and maintenance.",
    "It covers the entire lifecycle, from initial design to deployment and updates.",
    "Software engineering reduces errors but never removes the need for testing.",
    "Abstraction hides unnecessary details and exposes only the essential features.",
    "Modularity also improves maintainability and promotes code reuse.",
    "Encapsulation protects data integrity and makes systems more adaptable through loose coupling.",
    "Abstraction = hide complexity. Encapsulation = restrict access (e.g. private fields, public methods).",
    "A class is a blueprint; an object (e.g. myCar) is an instance of it.",
    "Inheritance creates hierarchies; polymorphism enables dynamic behaviour such as overriding.",
    "Strong type checking prevents e.g. assigning a string to an integer at compile time.",
    "Generics allow type-agnostic definitions for collections and methods.",
    "It is a disposal pattern for resources the garbage collector doesn't handle.",
    "It reduces memory leaks and manual memory management effort.",
    "The CLR also provides JIT compilation and garbage collection.",
    "This gives optimal performance at runtime.",
    "Converting IL to machine code is the CLR's JIT compiler job.",
    "It promotes code sharing and collaboration across teams.",
    "Other features: debugging tools (breakpoints, watches, call stack) and extensions.",
    "Solution Explorer manages files/dependencies; Properties shows attributes of the selected item.",
    "Create a new project, choose Console App, write Hello World, run and view the console output.",
    "Coursework is split: 25% design/project management/implementation and 25% algorithms & data structures.",
    "It is on Moodle with random questions and a time limit.",
    "It is group work but you get an individual mark.",
    "Also: working together on individual work, getting others to do your work, and unreferenced online code.",
    "If accepted you get a deferral/extension. Tell the lecturer ASAP.",

    // Week 2 (36)
    "git init creates a new repository; git clone <url> copies an existing one.",
    "Use git config --list to view the current configuration.",
    "git add <file> stages one file; git add . stages all.",
    "Staging prepares files; committing records them in the repository.",
    "Followed by git push -u origin main to push changes.",
    "git fetch only downloads updates; git pull fetches and merges.",
    "git branch only creates a branch; checkout switches to it.",
    "When branches have diverged, a three-way merge creates a new merge commit.",
    "Git highlights conflicting sections; edit, then git add <file> and git commit.",
    "Order: push to feature branch, create PR, add reviewers/comments, complete PR and merge.",
    "Reviewers can comment, suggest changes, approve, and use Resolve Comments.",
    "Agile values individuals and interactions over processes and tools.",
    "The four values: individuals/interactions, working software, customer collaboration, responding to change.",
    "Agile addresses these with faster delivery, flexibility and continuous feedback.",
    "Agile is incremental and iterative.",
    "The Product Owner prioritises the backlog; the Development Team delivers increments.",
    "Events: Sprint Planning, Daily Standups, Sprint Review, Sprint Retrospective. Sprint Backlog is an artifact.",
    "Product Backlog is the prioritised list; Sprint Backlog is tasks selected for the current sprint.",
    "Sprint Planning defines goals and selects backlog items.",
    "Order: Planning, Daily standups, Execution, Review (demo), Retrospective.",
    "Velocity = story points; cycle time = how long a task takes from start to finish.",
    "Boards = Kanban/backlogs; Repos = Git repositories.",
    "Benefits: early defect detection and consistent quality.",
    "Azure Repos also provides pull requests and code reviews.",
    "Result: faster releases and improved collaboration.",
    "Agile focuses on iterative development; together they deliver faster, more reliable software.",
    "Order: Requirements, Design & Architecture, Implementation, Testing, Deployment & Maintenance.",
    "Methods: interviews, surveys, stakeholder mapping.",
    "Techniques: use cases/user stories, workshops/brainstorming, observation, prototyping.",
    "Functional = what the system should do; non-functional = how it performs.",
    "Also user stories or use case diagrams.",
    "Outputs: architecture diagrams, component specifications, interface definitions.",
    "Component design splits the system into independent modules (payment, authentication, user management).",
    "Also use Git and conduct regular code reviews.",
    "Process: create a PR, assign reviewers, address feedback and merge.",
    "Integration tests interactions; system testing verifies the whole system.",

    // Week 3 (10)
    "Arrays use contiguous memory, are zero-based, hold one element type, and offer fast direct access.",
    "Fixed-size arrays suit cases where the number of elements is known in advance.",
    "Jagged arrays need extra memory for references; 2D arrays use contiguous memory, optimising access speed.",
    "2D arrays are a grid in contiguous memory; jagged arrays trade extra reference memory for flexibility.",
    "Other methods: Array.IndexOf(array, value), Array.Copy(source, destination, length), Array.Sort().",
    "IndexOf returns the position; Copy copies elements from one array to another.",
    "It implements IList and supports generics; higher-level abstraction than arrays.",
    "Doubling minimises reallocation overhead.",
    "Each node holds data plus references to the next (and optionally previous) node.",
    "Only node references are updated, but sequential access is slower than arrays.",

    // Week 4 (13)
    "A good hash function also distributes keys uniformly to minimise collisions.",
    "Hash functions must be deterministic, uniform and efficient.",
    "Chaining stores collided keys in a linked list or another structure.",
    "Methods include linear probing and quadratic probing.",
    "Load factor = stored elements / number of slots.",
    "Resizing means rehashing into a larger table when the load factor exceeds a threshold.",
    "Good hashing and collision handling keep operations near O(1).",
    "Vertices are nodes representing entities; edges represent relationships.",
    "Undirected graphs have no direction (e.g. mutual friendships).",
    "Weights represent costs or distances.",
    "DFS goes as far as possible along each branch before backtracking.",
    "BFS explores all vertices at the current depth level before moving deeper.",
    "It finds the shortest path from a source vertex to all other vertices in a weighted graph.",

    // Week 5 (19)
    "A foreign key is a field in one table that references the primary key in another.",
    "It creates the link between related tables.",
    "Relationship types: one-to-one, one-to-many, many-to-many.",
    "Normalisation organises data to reduce redundancy and improve integrity.",
    "1NF: eliminate duplicate columns and create separate tables for related data.",
    "2NF: non-key attributes depend on the whole key. 3NF eliminates transitive dependencies.",
    "ER diagrams show entities (Students, Courses), attributes (Name, Age) and relationships (enrol in).",
    "Schema design covers tables, fields, data types and constraints.",
    "A non-clustered index is a separate structure pointing to the data.",
    "Clustered orders the table's rows themselves; non-clustered is a separate lookup structure.",
    "CREATE TABLE defines structure: Students(StudentID INT PRIMARY KEY, Name VARCHAR(100), Age INT).",
    "DML manipulates data: INSERT, UPDATE, DELETE, SELECT.",
    "DCL controls access to data, e.g. GRANT SELECT ON Students TO User1;",
    "SELECT retrieves specific columns and rows; WHERE filters.",
    "UPDATE modifies existing records using SET and WHERE.",
    "DELETE removes records; INSERT adds rows; UPDATE modifies them.",
    "FULL OUTER JOIN returns all rows from both tables, matching or not. LEFT JOIN keeps all left rows plus matches from the right.",
    "INNER JOIN returns only matching rows. LEFT/RIGHT keep all rows from one side; FULL OUTER keeps all rows from both.",
    "WHERE specifies conditions to filter data, e.g. WHERE Age > 18.",
    
    // Week 6 (13)
    "e.g. \"Server=server_name;Database=database_name;User Id=username;Password=password;\". Avoid hardcoding; use config files.",
    "Benefits: reduced overhead and faster execution.",
    "Wrap in using, call BeginTransaction(); Commit() on success, Rollback() in catch.",
    "Pattern: try { Commit(); } catch { Rollback(); throw; }",
    "Disconnected architecture uses DataSet or DataTable to work offline.",
    "Connected architecture keeps the connection open.",
    "Also: avoid hardcoding connection strings; use configuration files.",
    "Code-First: entity classes -> relationships mapping -> migrations.",
    "Migrations update the database schema from code.",
    "Database-First scaffolds classes/context from an existing schema; Code-First creates the database from code.",
    "Code-First is ideal for greenfield projects; Database-First is best for legacy systems or existing databases.",
    "Query syntax: from s in context.Students where s.Age > 18 select s;",
    "Also minimise the number of database calls."
];